plugins:
  - serverless-python-requirements

custom:
  instance_state_table: ${self:service}-ECSCtrInstanceState
  task_state_table: ${self:service}-ECSTaskState
  task_digest_table: ${self:service}-ECSTaskDigest

  pythonRequirements:
    dockerizePip: true

service:
  name: ecs-slack

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Batch*"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:custom.instance_state_table}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.task_state_table}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.task_digest_table}"


functions:
  notify:
    name: ${self:service}-notify
    handler: main.lambda_handler
    description: Store ECS events in dynamodb and notify slack
    memorySize: 128
    timeout: 120
    reservedConcurrency: 1
    environment: ${file(.env.yml):notify.environment}
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ecs"
            detail-type:
              - "ECS Task State Change"
              - "ECS Container Instance State Change"


resources:
  Resources:
    ECSCtrInstanceState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.instance_state_table}
        AttributeDefinitions:
          - AttributeName: containerInstanceArn
            AttributeType: S
        KeySchema:
          - AttributeName: containerInstanceArn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True

    ECSTaskState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.task_state_table}
        AttributeDefinitions:
          - AttributeName: taskArn
            AttributeType: S
        KeySchema:
          - AttributeName: taskArn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True

    ECSTaskDigest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.task_digest_table}
        AttributeDefinitions:
          - AttributeName: startedBy
            AttributeType: S
        KeySchema:
          - AttributeName: startedBy
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True
